# Starter pipeline
# - task: PythonScript@0
#   inputs:
#     scriptSource: 'filePath'
#     scriptPath: '**/collatz_unittest.py'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

stages: 

  - stage: Build_and_Test
    jobs:
      - job: Test
        steps: 
        - script: python BCA_Technical_Interview/collatz_unittest.py
          displayName: Run unit tests
        
        - script: python BCA_Technical_Interview/collatz_conjecture.py
          displayName: Run collatz conjecture script
            
      - job: Build
        steps:
          # - script: docker build -t corbiegoonta/code_conts:collatz1 **/Dockerfile
          #   displayName: Build image
          - task: ContainerBuild@0
            inputs:
              dockerRegistryServiceConnection: 'Docker'
              repository: 'corbiegoonta/code_conts'
              Dockerfile: 'BCA_Technical_Interview/Dockerfile'
      
          - script: docker push corbiegoonta/code_conts:collatz
            displayName: Push image
          
          - script: docker run corbiegoonta/code_conts:collatz
            displayName: Run container

  - stage: Deploy_to_Dev
    jobs:
      - deployment: Deploy_to_developement
        environment: Development

  - stage: Deploy_to_Test
    jobs:

      - deployment: Deploy_to_testing
        environment: Testing

  - stage: Deploy_to_Prod
    jobs:

      - deployment: Deploy_to_production
        environment: Production



#   jobs:

#   - job: Test and Build

#     steps:
#     - script: python collatz_unittest.py
#       displayName: Run unit tests

#     - script: docker build -t corbiegoonta/code_conts:collatz1 .
#       displayName: Build image
    
#     - script: docker push corbiegoonta/code_conts:collatz
#       displayName: Push image
    
#     - script: docker run -it corbiegoonta/code_conts:collatz
#       displayName: Run container

#     - script: echo Hello, world!
#       displayName: 'Run a one-line script'

#     - script: |
#         echo Add other tasks to build, test, and deploy your project.
#         echo See https://aka.ms/yaml
#       displayName: 'Run a multi-line script'
