variables:
  starting_number: 10

trigger:
- main

pool: Default

stages: 

  - stage: Continuous_Integration
    jobs:
      - job: Test
        steps: 
        - script: python BCA_Technical_Interview/collatz_unittest.py 
          displayName: Run unit tests
        
        - script: python BCA_Technical_Interview/collatz_conjecture.py $(starting_number)
          displayName: Run collatz conjecture script
            
      - job: Build
        dependsOn: Test
        steps:

          - task: ContainerBuild@0
            inputs:
              dockerRegistryServiceConnection: 'Docker'
              repository: 'corbiegoonta/code_conts'
              Dockerfile: 'BCA_Technical_Interview/Dockerfile'
      
          - script: docker push corbiegoonta/code_conts:collatz
            displayName: Push image
          
          - script: docker run corbiegoonta/code_conts:collatz
            displayName: Run container

  - stage: Continuous_Deployment
    dependsOn: Continuous_Integration
    jobs:
      - deployment: Deploy_to_development
        environment: Development

      - deployment: Deploy_to_testing
        dependsOn: Deploy_to_development
        environment: Testing

      - deployment: Deploy_to_production
        dependsOn: Deploy_to_testing
        environment: Production
