#pipeline template

parameters:
- name: pipeline_trigger
  type: string
  default: main

- name: vm_pool
  type: string
  default: vmImage

- name: vm_image
  type: string
  default: 'ubuntu-latest'

- name: cd_dependency
  type: string 

- name: build_dependency
  type: string 
  

trigger:
  - ${{parameters.pipeline_trigger}}

pool:
  ${{parameters.vm_pool}}: ${{parameters.vm_image}}

stages:
  - stage: Continuous_Integration
    jobs:
      - job: Test 
      - job: Build
        dependsOn: ${{parameters.build_dependency}}
  - stage: Continuous_Deployment
    dependsOn: ${{parameters.cd_dependency}}
    jobs:
      

