variables:
  starting_number: 10

trigger:
  - main

pool: default

# pool:
#   vmImage: ubuntu-latest

stages:
  - stage: Continuous_Integration
    jobs:
      - job: Test 
        steps: 
        - script: python BCA_Technical_Interview/collatz_unittest.py
          displayName: Run unit tests
        
        - script: python BCA_Technical_Interview/collatz_conjecture.py $(starting_number)
          displayName: Run collatz conjecture script

      - job: Build
        dependsOn: Test
        steps:
        - template: docker_bpr_template.yaml
          parameters: 
            container_registry: 'Docker'
            container_repository: 'corbiegoonta/code_conts'
            dockerfile: 'BCA_Technical_Interview/Pipeline/Dockerfile'
            image_tag: 'collatz'
            
  - stage: Continuous_Deployment
    dependsOn: Continuous_Integration
    jobs:
    - template: env_deployments_template.yaml
      parameters:
        deployment_name: Deploy_to_Dev
        deployment_environment: Development
    - template: env_deployments_template.yaml
      parameters:
        deployment_name: Deploy_to_Test
        deployment_environment: Testing
        deployment_dependency: Deploy_to_Dev
    - template: env_deployments_template.yaml
      parameters:
        deployment_name: Deploy_to_Prod
        deployment_environment: Production
        deployment_dependency: Deploy_to_Test