variables:
  starting_number: 10

trigger:
  - main

pool: default

stages:
  - stage: Continuous_Integration
    jobs:
      - job: Test 
        steps: 
        - script: python BCA_Technical_Interview/collatz_unittest.py
          displayName: Run unit tests
        
        - script: python BCA_Technical_Interview/collatz_conjecture.py $(starting_number)
          displayName: Run collatz conjecture script

      - job: Build
        dependsOn: Test
        steps:
        - template: docker_bpr_template.yaml
          parameters: 
            container_registry: 'Docker'
            container_repository: 'corbiegoonta/code_conts'
            dockerfile: 'BCA_Technical_Interview/Dockerfile'
            image_tag: 'collatz'
            
  - stage: Continuous_Deployment
    dependsOn: Continuous_Integration
    jobs:
    - template: deployments_template.yaml
      parameters:
        deployment_name: Deploy_to_Dev
        deployment_environment: Development
        deployment_dependency: ''
    - job: Deploy__Function
      steps:
      - task: AzureFunction@1
        inputs:
          function: 'https://corbfunct.azurewebsites.net/api/big_trig'
          key: 'ExSR6JAS_4lyuPZ-rncQV3ZPwTyzH8UInMITtVNQuuc3AzFubzx45Q=='
          method: 'POST'
          body: '{"name" : "corbie"}'
          waitForCompletion: 'false'
      # - task: AzureFunction@1
      #   inputs:
      #     function: 'https://corbfunct.azurewebsites.net/api/int_func?code=2jQTrawOhFMBdt-cbiBB_OUQFD97KKAtlcEfu-iSG-IbAzFuHHLrjw=='
      #     key: 'c-qC-lxXXtzNKFadiF1Ec9MuMKnPZ0ey00x0yFYdnqYJAzFujFgNTw=='
      #     method: 'GET'
      #     waitForCompletion: 'false'
      