version: '3.9'

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://corbie:postgres@db:5432/finance_db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: corbie
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000