name: CI Pipeline

on: 
  push:
    branches: 
      - main
      
  # pull_request:
  #   branches: ["main"]
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AI/Finance/requirements.txt
    # Lint with ruff for flake8
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check .
    # Run tests with pytest
    - name: Run tests
      run: |
        pip install pytest
        pytest || echo "No tests yet"

    # - name: Build and run application (optional)
    #   run: |
    #     uvicorn app.main:app --host
